var namespace_newtonsoft_1_1_json_1_1_serialization =
[
    [ "SLTCamelCasePropertyNamesExceptDictionaryKeysContractResolver", "class_newtonsoft_1_1_json_1_1_serialization_1_1_s_l_t_camel_case_property_names_except_dictionary_keys_contract_resolver.html", "class_newtonsoft_1_1_json_1_1_serialization_1_1_s_l_t_camel_case_property_names_except_dictionary_keys_contract_resolver" ]
];